In [1]:
import torch

In [6]:
randint = torch.randint(-100,100,(6,))
randint

tensor([ 90,  29, -24, -16,   6, -48])

In [8]:
tensor = torch.tensor([[0.1,1.2],[4.4,2.2],[5.5,6.6]])
tensor

tensor([[0.1000, 1.2000],
        [4.4000, 2.2000],
        [5.5000, 6.6000]])

In [9]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [15]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [16]:
logspace = torch.logspace(-10,10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [17]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
a = torch.empty((2,3),dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])