In [5]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [7]:
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f'{elapsed_time:.8f}')

0.0000


In [11]:
torchrand1 = torch.rand(100,100,100,100).to(device)
torchrand2 = torch.rand(100,100,100,100).to(device)
nprand1 = torch.rand(100,100,100,100)
nprand2 = torch.rand(100,100,100,100)

start_time = time.time()

rand = (torchrand1 @ torchrand2)

end_time = time.time()
elapsed_time = end_time - start_time
print(f'{elapsed_time:.8f}')

start_time = time.time()

rand = np.multiply(nprand1,nprand2)

end_time = time.time()
elapsed_time = end_time - start_time
print(f'{elapsed_time:.8f}')

0.04311061
0.11665177


C:\Users\kiraq\AppData\Local\Temp\ipykernel_8156\894573031.py:16: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(nprand1,nprand2)


In [25]:
probability = torch.tensor([0.1,0.9])
samples = torch.multinomial(probability,num_samples = 10, replacement = True)
samples

tensor([0, 1, 1, 1, 0, 1, 0, 1, 1, 1])

In [27]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])),dim=0)
out

tensor([1, 2, 3, 4, 5])

In [30]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [31]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [33]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [34]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [37]:
input = torch.zeros([2,3,4])
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [40]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [42]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias = False)
linear(sample)

tensor([-6.7775, -0.4515, -4.0566], grad_fn=<SqueezeBackward4>)

In [45]:
import torch.nn.functional as F
tensor1 = torch.tensor([1.0,2.0,3.0])
softmax_output = F.softmax(tensor1,dim = 0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [49]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
b @ a

tensor([[ 76, 100],
        [103, 136]])

In [54]:
int_64 = torch.randint(1,(3,2)).float()
float_32 = torch.rand(2,3)
result = torch.matmul(int_64, float_32)
result

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])